"use client";

import { useState } from "react";

const plans = [
  { name: "Starter", detail: "A confident first step", price: 6000, tag: "For curious beginners", classes: "4 classes / month", features: ["1 group class / week", "Tactics workbook", "Monthly progress note" ] },
  { name: "Focus", detail: "The most popular path", price: 11000, tag: "For steady progress", featured: true, classes: "8 classes / month", features: ["2 live classes / week", "Weekly game review", "Practice arena access", "Parent check-in"] },
  { name: "Champion", detail: "For serious young players", price: 18500, tag: "For tournament goals", classes: "8 classes / month", features: ["1:1 coaching", "Tournament preparation", "Personal opening plan", "Priority support"] },
];

const faqs = [
  ["What age groups do you teach?", "Our core academy is for children aged 5–15. We group students by age and playing level, so a curious beginner and an ambitious tournament player both get the right challenge."],
  ["Does my child need chess experience?", "Not at all. Our Starter pathway is designed for complete beginners. We begin with the board, pieces and simple checkmates, then build toward tactics and independent thinking."],
  ["Are classes online or in person?", "We offer live online classes across Pakistan, plus limited in-person cohorts in Islamabad. Every class is interactive, small and taught by a real coach."],
  ["How do the trial classes work?", "Book a 30-minute introduction for Rs 1,000. Your child plays a few friendly positions with Coach Ayesha, and you leave with a suggested learning path."],
];

function ChessBoard() {
  const pieces = ["♜", "♞", "♝", "♛", "♚", "♝", "♞", "♜", "♟", "♟", "♟", "♟", "♟", "♟", "♟", "♟", "♙", "♙", "♙", "♙", "♙", "♙", "♙", "♙", "♖", "♘", "♗", "♕", "♔", "♗", "♘", "♖"];
  return <div className="board" aria-label="Decorative chess board">{Array.from({ length: 64 }, (_, index) => <div className={`square ${(Math.floor(index / 8) + index) % 2 === 0 ? "light" : "dark"}`} key={index}>{pieces[index] && <span className={index < 16 ? "black-piece" : "white-piece"}>{pieces[index]}</span>}</div>)}</div>;
}

export default function Home() {
  const [openFaq, setOpenFaq] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <main>
      <nav className="nav shell"><a className="brand" href="#top"><img className="brand-logo" src="/logo.png" alt="NextGen Chess Academy" /></a><div className={`nav-links ${menuOpen ? "is-open" : ""}`}><a href="#method" onClick={() => setMenuOpen(false)}>Our method</a><a href="#programs" onClick={() => setMenuOpen(false)}>Programs</a><a href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a></div><a className="button button-small button-dark nav-cta" href="https://wa.me/923170264298?text=Hi%20NextGen%20Chess%20Academy%2C%20I%27d%20like%20to%20book%20a%20trial%20lesson%20in%20Islamabad.">Book a trial <span>↗</span></a><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? "×" : "☰"}</button></nav>
      <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Pakistan&apos;s female-led chess academy</p><h1>Raise a thinker.<br /><em>Not just a player.</em></h1><p className="hero-text">A warm, rigorous chess home for curious kids aged 5–15. We turn every position into a lesson in focus, courage and clever problem-solving.</p><div className="hero-actions"><a className="button button-coral" href="https://wa.me/923170264298?text=Hi%20NextGen%20Chess%20Academy%2C%20I%27d%20like%20to%20find%20the%20right%20trial%20path%20for%20my%20child.">Find your child&apos;s path <span>↗</span></a><a className="text-link" href="#method">See how we teach <span>↓</span></a></div><div className="trust-row"><div className="avatars"><span>SA</span><span>HZ</span><span>AR</span><span>+</span></div><p><strong>500+ young minds</strong><br />learning with us across Pakistan</p></div></div><div className="hero-art"><div className="art-note note-top">Think<br /><strong>three moves</strong><br />ahead.</div><ChessBoard /><div className="art-note note-bottom"><span>01</span> Every move<br />has a reason.</div><div className="line-doodle" /></div></section>
      <div className="ticker"><div className="ticker-inner"><span>FOCUS</span><i>✦</i><span>TACTICS</span><i>✦</i><span>CONFIDENCE</span><i>✦</i><span>PROBLEM-SOLVING</span><i>✦</i><span>FOCUS</span><i>✦</i><span>TACTICS</span></div></div>
      <section className="intro shell" id="method"><div className="section-label">01 / Our approach</div><div><h2>Chess is the game.<br /><span>Thinking is the goal.</span></h2><p className="intro-lead">We teach children how to pause, see possibilities and make brave decisions. The board is simply where the magic starts.</p><a className="text-link coral-link" href="#programs">Explore our programs <span>↗</span></a></div></section>
      <section className="method-grid shell"><div className="method-card coral-card"><div className="method-number">01</div><div className="method-icon">◒</div><h3>Build deep focus</h3><p>Short puzzles and playful challenges make concentration feel like a superpower, not a chore.</p></div><div className="method-card yellow-card"><div className="method-number">02</div><div className="method-icon">♟</div><h3>Make smart moves</h3><p>Kids learn to spot patterns, weigh choices and understand the story behind every move.</p></div><div className="method-card ink-card"><div className="method-number">03</div><div className="method-icon">↗</div><h3>Grow with courage</h3><p>We celebrate the thinking, especially when a plan doesn&apos;t work. That&apos;s where confidence grows.</p></div></section>
      <section className="programs section-band" id="programs"><div className="shell"><div className="section-label light-label">02 / Find their fit</div><div className="programs-heading"><h2>One academy.<br /><em>Three ways to grow.</em></h2><p>Thoughtful paths for every age, level and little chess dream.</p></div><div className="program-list"><article><span className="program-index">01</span><div><h3>Little Knights <small>ages 5–7</small></h3><p>Story-led first steps into the world of chess, with games that make learning feel like play.</p></div><a href="#trial" aria-label="Explore Little Knights">↗</a></article><article><span className="program-index">02</span><div><h3>Young Strategists <small>ages 8–11</small></h3><p>Tactics, patterns and practical games for children ready to think one move ahead.</p></div><a href="#trial" aria-label="Explore Young Strategists">↗</a></article><article><span className="program-index">03</span><div><h3>Rising Champions <small>ages 12–15</small></h3><p>Serious improvement with tournament prep, opening plans and confident decision-making.</p></div><a href="#trial" aria-label="Explore Rising Champions">↗</a></article></div></div></section>
      <section className="coach shell"><div className="coach-portrait"><div className="portrait-shape"><span>AN</span></div><div className="portrait-stamp">COACH<br />ARSHIA<br /><b>♥</b></div></div><div className="coach-copy"><div className="section-label">03 / Meet your coach</div><h2>“There is no<br /><em>wrong way</em> to learn.”</h2><p>Coach Arshia Naveed believes every child has a chess voice worth listening to. A national-level player and certified educator, she brings structure, warmth and a lot of joy to every lesson.</p><div className="coach-stats"><span><strong>12+</strong> years playing</span><span><strong>8</strong> years teaching</span><span><strong>1,200+</strong> students</span></div><a className="text-link coral-link" href="#trial">Meet the team <span>↗</span></a></div></section>
      <section className="pricing shell" id="pricing"><div className="section-label">04 / Simple pricing</div><div className="pricing-head"><div><h2>Choose their<br /><em>next move.</em></h2><p>Flexible monthly plans for families in Islamabad. Pause or switch paths anytime.</p></div><div className="pricing-note"><span>↗</span> All plans include a<br />friendly progress check-in</div></div><div className="plans">{plans.map((plan) => <article className={`plan ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured && <div className="popular">Most popular</div>}<p className="plan-name">{plan.name}</p><p className="plan-detail">{plan.detail}</p><p className="plan-tag">{plan.tag}</p><div className="class-count"><strong>{plan.classes}</strong><span>live coaching sessions</span></div><div className="price"><span>Rs.</span>{plan.price.toLocaleString()}<small>/ month</small></div><ul>{plan.features.map((feature) => <li key={feature}><span>✓</span>{feature}</li>)}</ul><a className={`button ${plan.featured ? "button-coral" : "button-outline"}`} href="https://wa.me/923170264298?text=Hi%20NextGen%20Chess%20Academy%2C%20I%27m%20interested%20in%20the%20{plan.name}%20plan%20for%20my%20child.">Choose {plan.name} <span>↗</span></a></article>)}</div></section>
      <section className="testimonial"><div className="shell testimonial-inner"><div className="quote-mark">“</div><blockquote>My daughter used to rush through everything. Now she pauses, thinks and explains her ideas. Chess gave her a new kind of confidence.</blockquote><p>— Sana, parent of Maham <span>★★★★★</span></p></div></section>
      <section className="faq shell" id="faq"><div className="section-label">05 / Good to know</div><div className="faq-layout"><h2>Questions,<br /><em>answered.</em></h2><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span><b>{openFaq === index ? "−" : "+"}</b></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></div></section>
      <section className="trial shell" id="trial"><div className="trial-inner"><div><p className="eyebrow dark-eyebrow"><span className="eyebrow-dot" /> Start with a hello</p><h2>Ready to make<br /><em>their first move?</em></h2><p>Chat with Coach Ayesha on WhatsApp and book a friendly trial lesson in Islamabad.</p></div><a className="button button-dark" href="https://wa.me/923170264298?text=Hi%20NextGen%20Chess%20Academy%2C%20I%27d%20like%20to%20book%20a%20trial%20lesson%20in%20Islamabad.">Chat on WhatsApp <span>↗</span></a><div className="trial-scribble">Let&apos;s play!</div></div></section>
      <footer className="footer shell"><a className="brand" href="#top"><img className="brand-logo" src="/logo.png" alt="NextGen Chess Academy" /></a><p>Made for curious minds<br />in Islamabad and beyond.</p><div className="footer-links"><a href="#programs">Programs</a><a href="#pricing">Pricing</a><a href="https://wa.me/923170264298">WhatsApp us</a></div><small>© 2026 NextGen Chess Academy</small></footer>
    </main>
  );
}
